### ISSUE TITLE
使用weex src/foo.vue 预览在电脑浏览器上路由router-view显示正常，用手机扫出来的就不出来

### ISSUE THREAD

**Issue by MaLoneGitHub** [open-dingtalk/weex-dingtalk-issues#11]
![dbx53x9 i2 d dwi 9rr](https://user-images.githubusercontent.com/13703597/27414637-2987b0d8-5735-11e7-8c94-6b0fe45b9236.png)
![7n f lnsxznk 21re det7](https://user-images.githubusercontent.com/13703597/27414644-33d1c5e2-5735-11e7-8088-9efe15780f1c.png)

**Comment by icepy** [comment]
用的是我们的脚手架？

**Comment by MaLoneGitHub** [comment]
额，不是的，是不是weex 预览只能预览单个页面，import进来的页面看不到？？？

**Comment by icepy** [comment]
是的，只能预览单个页面。
