### ISSUE TITLE
不能在钉钉环境中调试weex

### ISSUE THREAD

**Issue by MaLoneGitHub** [open-dingtalk/weex-dingtalk-issues#12]
![56ket 8d sa3 j j5j d3n](https://user-images.githubusercontent.com/13703597/27420246-9091ac3a-5757-11e7-9330-6d203567352f.png)
…]()
电脑端也出现这个
![twcuyr4wr sm3y cl0y3 r](https://user-images.githubusercontent.com/13703597/27420300-d3fa46d0-5757-11e7-9108-9bc0a178f955.png)

手机端：进入http://192.168.31.103:8088/weex/weex-bundle-watch.js?dd_wx_tpl=http://192.168.31.103:8088/weex/weex-bundle-watch.js&dd_wx_debug=ws://192.168.31.103:8088/debugProxy/native这个地址,也能出现页面，
但是电脑上的不会出现调试的页面

**Comment by icepy** [comment]
调试包只支持Mac，需要安装在模拟器中。

**Comment by aLuckGirl** [comment]
调试包只支持Mac上，需要安装在模拟器中。   在哪里下载的，能发我一下吗
