### ISSUE TITLE
使用weex debug ，手机能进入页面，但是谷歌浏览器没有进入调试页面

### ISSUE THREAD

**Issue by MaLoneGitHub** [open-dingtalk/weex-dingtalk-issues#13]
电脑端执行weex debug
![image](https://user-images.githubusercontent.com/13703597/27472901-c620f544-582f-11e7-8304-f6f46a474b1f.png)
谷歌浏览器能够弹出页面
![image](https://user-images.githubusercontent.com/13703597/27472944-e87edd4a-582f-11e7-880e-5c69c93624b3.png)
手机端的点击这个链接
![image](https://user-images.githubusercontent.com/13703597/27472868-a810fd6a-582f-11e7-8e06-dc35ba26ead7.png)
能够进入页面
![dingtalk20170623162531](https://user-images.githubusercontent.com/13703597/27473136-a816e8aa-5830-11e7-9ab0-62d789abbc58.png)

但是谷歌浏览器不会进入调试界面

**Comment by icepy** [comment]
安装我给你的调试包
