### ISSUE TITLE
v-for动态绑定className时，web端没问题，iOS和安卓会报错

### ISSUE THREAD

**Issue by XieAn2016** [open-dingtalk/weex-dingtalk-issues#14]
问题
v-for动态绑定className时，web端没问题，iOS和安卓会报错：报错信息如下图
![2](https://user-images.githubusercontent.com/20041329/27538265-b5d7ca06-5aa9-11e7-97bc-bea4a0e71867.png)
【用图片中方法无效】
![1](https://user-images.githubusercontent.com/20041329/27538185-611349c8-5aa9-11e7-8e83-ff34cf1e633a.png)

业务逻辑
想进行v-for渲染className

代码链接
http://dotwe.org/vue/019899be8bbc74a96e28e2b0266beaf0

**Comment by icepy** [comment]
使用数组表达式的方式
