### ISSUE TITLE
构建后的weex-bundle.js缓存问题

### ISSUE THREAD

**Issue by Mr-xue** [open-dingtalk/weex-dingtalk-issues#15]
构建完成后，从应用后台配置好首页访问路径，测试正常，能正常进入Native模式。
但是文件修改后，重新构建部署后，访问测试应用时的代码没进行更新，用手机清除缓存，重新进入钉钉也没变化。
而且如果以后修改文件，每次都这样，我们不能针对每个用户去引导清除缓存的类似操作。
有什么方法可以避免bundle.js缓存，或者可以从我们这边强制更新么？这个问题该怎么解决？

**Comment by icepy** [comment]
你自己要做版本控制
