### ISSUE TITLE
在weex中打开多个web view是否支持view之间的交互？

### ISSUE THREAD

**Issue by duoduoing** [open-dingtalk/weex-dingtalk-issues#16]
先打开了一个页面A，在打开一个页面B，能否支持在页面B调用页面A的某些函数？正常的业务场景是，从一个拥有列表条数的页面A进入到一个列表页B，在列表页B执行审批、删除之类的操作，列表数据势必要变更，在B页面很容易控制自己去刷新列表，但是这时候也要控制A页面的条数进行刷新。
我想要问的就是是否weex是否支持在这种场景下，B页面执行A页面的函数？

**Comment by icepy** [comment]
既然用weex为什么还要加多个webview？这在性能上就不可取。

这个问题不是weex容器的问题，界面只可能存在一个，当你打开B页面时，如果你用`openLink`，那么这是一个VC级别的转场，如果你使用vue-router，那么这仅仅是组件级别的载入和卸载。

**Comment by duoduoing** [comment]
如果用weex的容器载入vue组件A，那么当载入一个新的组件B的时候，组件A是没有卸载的吧？A和B是同时存在的吧？这两个组件之间可以交互通信吗？

**Comment by duoduoing** [comment]
@icepy 如果用weex的容器载入vue组件A，那么当载入一个新的组件B的时候，组件A是没有卸载的吧？A和B是同时存在的吧？这两个组件之间可以交互通信吗？

**Comment by icepy** [comment]
请自行学习vue，[https://cn.vuejs.org/](https://cn.vuejs.org/) @duoduoing

**Comment by duoduoing** [comment]
@icepy weex debug的包有安卓的吗？你在群里叫什么啊？
