### ISSUE TITLE
android 7.1.2从钉钉客户端无法启动weex

### ISSUE THREAD

**Issue by ScorpiusJin** [open-dingtalk/weex-dingtalk-issues#19]
手机机型： google pixel  android 7.1.2
钉钉版本：3.5.0

1. 钉钉通过 http://h5host?dd_wx_tpl=weexhost.js 的方式访问，测试了10台设备，有一台android 7.1.2的无法使用weex，打开了h5的界面。
2. 通过weex playground访问 http://weexhost.js ，所有设备都可以打开weex界面。

![ding](https://user-images.githubusercontent.com/1516678/27585052-2c9af1ae-5b6d-11e7-9ee3-407c13f94a18.jpg)
![weex](https://user-images.githubusercontent.com/1516678/27585053-2c9d39d2-5b6d-11e7-9c10-ac92e9d1bc0c.jpg)

**Comment by injekt** [comment]
我们发现部分android7.1的设备确实有这个问题，会降级到h5。目前原因正在调查
