### ISSUE TITLE
ios端 native err

### ISSUE THREAD

**Issue by lihqi** [open-dingtalk/weex-dingtalk-issues#20]
![e20170628180736](https://user-images.githubusercontent.com/25564864/27631983-ef297b4a-5c2c-11e7-9d1e-33de5c9da952.png)

**Comment by lihqi** [comment]
![r20170629145646](https://user-images.githubusercontent.com/25564864/27675115-3d4c6fa4-5cdb-11e7-8580-a9ead862189b.png)
这error 会导致input框的 focus方法失效
在ios出现概率低、会报错，在安卓上会失效但不会报错

**Comment by kfeagle** [comment]
@lihqi 有没有具体demo，看来是组件已经失效了

**Comment by lihqi** [comment]
在playground里如何使用vue-router呢

**Comment by lihqi** [comment]
@kfeagle 在playground里如何使用vue-router呢，项目中用的vue-router切换路由

**Comment by icepy** [comment]
@lihqi playground里不允许载入模块
