### ISSUE TITLE
页面渲染有时候会出现不可预知的问题

### ISSUE THREAD

**Issue by Mr-xue** [open-dingtalk/weex-dingtalk-issues#24]
![image](https://user-images.githubusercontent.com/11676811/27811109-e76de3fc-6094-11e7-99be-ee0269f6181d.png)

如图，有时候页面渲染的时候部分iconfont渲染的有问题，红框处的图标都只显示了一半，再次进来就好了。
绿框处有时有些图片显示空白，重进后也是好的。

以上情况安卓机有概率出现，苹果机暂未发现。

**Comment by icepy** [comment]
@Mr-xue 给能复现的例子
