### ISSUE TITLE
text-overflow:ellipsis三端体验不一致

### ISSUE THREAD

**Issue by lihqi** [open-dingtalk/weex-dingtalk-issues#27]
text-overflow:ellipsis
在前面是中文后面出现英文的情况下体验不一致
复现地址：http://dotwe.org/vue/f7c2cfe91afbc343c9a354e69b5e5e07
安卓
![screenshot_2017-07-07-15-25-50-185_com alibaba weex](https://user-images.githubusercontent.com/25564864/27947608-2dc88d66-6329-11e7-9690-eae1c34d380f.png)
ios
![img_0544](https://user-images.githubusercontent.com/25564864/27947618-370fd582-6329-11e7-9a47-7c47a09217c0.PNG)
web
![dingtalk_im_175187214](https://user-images.githubusercontent.com/25564864/27947627-3c1cefce-6329-11e7-8516-56de3e977da4.JPG)

**Comment by acton393** [comment]
hi @lihqi   这个现象的是拆次算法导致的， 后面的英文单词太长，Android和h5 里面第一行绘制不下会绘制到第二行， lines:1指定了只显示一行，所以只绘制第一行，其他ellipse 显示，iOS  拆次算法应该是有拼写检查，是否是单词， 如果不是单词就按照字符拆分，所以会看到iOS 绘制一部分中文一部分英文，剩下的ellipse

拆次算法暂时不能更改， 对于这种长单词来说确实会出现目前现象
