### ISSUE TITLE
weex的picker组件在安卓手机的钉钉客户端里失效

### ISSUE THREAD

**Issue by lihqi** [open-dingtalk/weex-dingtalk-issues#29]
picker组件的地址
http://dotwe.org/vue/7a2c0cf6e94f87a67bdae005f57cfada
在钉钉里打开需要加前缀 在安卓客户端里无效
改用JSAPI里的biz.util.chosen下拉组件
但是会出现一个问题：如果快速点击的话，会出现层叠的问题，现在的解决办法是加300ms的延迟，有更好的解决办法么？

**Comment by icepy** [comment]
自己锁一下，就像click事件一样，前面一个click没有回调完成之前都不要调用。
