### ISSUE TITLE
调用slider组件，出现无限倍增及卡顿的问题

### ISSUE THREAD

**Issue by Mr-xue** [open-dingtalk/weex-dingtalk-issues#3]
此问题在dotwe上没有出现，但同样的代码在web测试环境中会出现无限倍增的问题，隔一段时间就会创建出很多幻灯片元素。而且幻灯片切换一场卡顿，不顺畅。
dotwe：http://dotwe.org/vue/195a429dbdea67b7083826f2f77591c4

当在卡顿的幻灯片上手动进行拖拽切换的时候，有时候控制台会出现以下错误。
![image](https://user-images.githubusercontent.com/11676811/27214426-f77e3c14-529e-11e7-9e4c-d6f8da6e1f79.png)

**Comment by icepy** [comment]
你的web测试环境，加过什么其他特别的代码吗？同样的代码，在一个干净的环境里不会出现你说的问题。

**Comment by Mr-xue** [comment]
没加任何其他代码，这个我已经试过了。

**Comment by icepy** [comment]
你把你的环境信息贴一下

**Comment by Mr-xue** [comment]
![image](https://user-images.githubusercontent.com/11676811/27216088-c7e5224e-52a6-11e7-9db2-5fce892ec7bf.png)
![image](https://user-images.githubusercontent.com/11676811/27216103-d81a558a-52a6-11e7-9d5d-914a9846c67b.png)
![image](https://user-images.githubusercontent.com/11676811/27216137-f65c0d86-52a6-11e7-8644-f4a42125c2ee.png)

**Comment by MrRaindrop** [comment]
升到 0.11.50 试试，后面的版本 slider 重构了，这个问题应该没有了

**Comment by Mr-xue** [comment]
升级完，倍增问题两端都解决了。但web模式下幻灯片组件的尺寸不对，显示的是750的尺寸，没有缩放，页面也被撑开了。

**Comment by MrRaindrop** [comment]
@Mr-xue 能在 dotwe 里写个 demo 复现一下么？

**Comment by Mr-xue** [comment]
问题开始的dotwe地址里面就是
