### ISSUE TITLE
建议 dingtalk lib 包升级时提供 changelog

### ISSUE THREAD

**Issue by yardfarmer** [open-dingtalk/weex-dingtalk-issues#31]
dingtalk lib 升级了，开发者不能清楚的了解 api 有什么变化，是否需要升级。

![image](https://user-images.githubusercontent.com/1446828/28195047-906891b8-687a-11e7-8bfa-b59efc7c5b97.png)

**Comment by icepy** [comment]
这个建议，我记下了。

其实，是有update的，https://open-doc.dingtalk.com/docs/doc.htm?spm=a219a.7629140.0.0.jDhzGt&treeId=357&articleId=106881&docType=1
