### ISSUE TITLE
dd.biz.util.share在ios下报错

### ISSUE THREAD

**Issue by godkillCK** [open-dingtalk/weex-dingtalk-issues#34]
环境：weex
调用dd.biz.util.share在ios下报：This JS-API can not be called in this container
android下是好的

**Comment by godkillCK** [comment]
这个什么时候能解决不？现在项目微应用使用的weex开发，不可能给切换到h5了，或者提供什么兼容性解决方案- -
dingtalk的日志：
Sep  5 23:06:22 DingTalk[80394]: -[LAWeexViewContainer pluginInstance:jsapiShouldCall:] #312 [INFO] Auth permitted for JS-API = biz.util.share
Sep  5 23:06:22 DingTalk[80394]:  #38 [WARN] ui.tab must be called in DTWebViewController

**Comment by icepy** [comment]
iOS Weex容器暂时不支持分享api
