### ISSUE TITLE
应用weex中的<refresh><loading>上拉与下拉刷新，3端体验不一致，安卓没问题，iOS都不行，web<refresh>可以

### ISSUE THREAD

**Issue by XieAn2016** [open-dingtalk/weex-dingtalk-issues#4]
问题：应用weex中的refresh，loading上拉与下拉刷新，3端体验不一致，安卓没问题，iOS都不行，web<refresh>可以

- 必须提供完整的环境信息和必要的错误信息
![img_1791](https://user-images.githubusercontent.com/20041329/27218486-e5411532-52b0-11e7-9e20-104a4afcaeaa.png)
![img_1792](https://user-images.githubusercontent.com/20041329/27218488-e62d981c-52b0-11e7-8c51-6dfdd76423ab.png)
![20170616_162217_rmscr](https://user-images.githubusercontent.com/20041329/27218510-fdfed67c-52b0-11e7-9a65-e629d65f8a02.jpg)

- 简单介绍一下你的业务逻辑
需要用<refresh><loading>做一个上拉和下拉刷新数据的操作

- 可以再 http://dotwe.org/vue 中复现你的问题
[http://dotwe.org/vue/32dfa19bb539739a5aa5176ad4781149](url)

- 提供你可能错误的代码，必须是一个完整的Demo

**Comment by icepy** [comment]
用钉钉的客户端跑试一试

**Comment by XieAn2016** [comment]
现象是一样的，安卓没问题，iOS滑动无反应

**Comment by acton393** [comment]
在iOS 上由于 Scroller 的contentSize 小于scroller 本身高度所以导致不能滑动
