### ISSUE TITLE
css在web模式下跟Native下表现不一致

### ISSUE THREAD

**Issue by Mr-xue** [open-dingtalk/weex-dingtalk-issues#5]
示例代码：http://dotwe.org/vue/24472a79a50be345771d0fce1d019e03（这是正常的）

测试环境Native下：菜单是竖向的
![_20170616174412](https://user-images.githubusercontent.com/11676811/27221540-7d39118c-52bb-11e7-9e2f-4eef441173d6.jpg)

测试环境web下：菜单正常，但是字体尺寸太大，没有进行缩放。

![_20170616174210](https://user-images.githubusercontent.com/11676811/27221546-82758a54-52bb-11e7-89cf-f2ac1e155b6f.png)

**Comment by icepy** [comment]
你要基于750px来布局，如果你的容器内容超出了，自然变成这样。

**Comment by Mr-xue** [comment]
我是按照750的尺寸来的。
你看下我的示例代码：http://dotwe.org/vue/5473c2a563a62e1674747fc5caa7934f
同样的代码在dotwei里面表现是正常的。
目前我发现的问题是：
1.假如我按照750设计图中的尺寸来设置元素大小，原生模式下都没问题，正常缩放了。web模式下元素没有进行缩放，直接按照750的尺寸展示出来。
比如下图中的字体设计图中是24号字，实际展示大小应为12号字，原生没问题，web是按照24号字展示的。
幻灯片是750*312，原生没问题，web高度还是312，没进行缩放，导致高度撑高很多有一大块留白。

2.有些样式得不到统一。比如那四个小图标，应该在一行，原生模式下却是竖向排列的

在我的原生环境是这样：
![image](https://user-images.githubusercontent.com/11676811/27249024-d4a29d84-533e-11e7-829e-7f4e7e03336a.png)

在我的web环境是这样：
![image](https://user-images.githubusercontent.com/11676811/27249041-053dbf0a-533f-11e7-90fa-325fa48e9c79.png)

**Comment by icepy** [comment]
top-nav-list定义四分的宽度，750/4，容器的大小都要显示的指明，字体大小都要显示的指明大小。

**Comment by Mr-xue** [comment]
我排查后发现导航样式失效的原因不是你说的，而是因为导航用了id去写样式，换成class就行了。但不知道为什么在dotwe里面用id就没问题。
其次我所有按照750尺寸来写的样式，在web模式下都没有进行缩放，比如这个里面的字体，
在web模式下都是显示的24号字体，没有进行缩放，但样式里面都是按照750的尺寸写的。  http://dotwe.org/vue/5473c2a563a62e1674747fc5caa7934f

**Comment by foolyoghurt** [comment]
@Mr-xue  dotwe 里展示的是 web 的，自然标准的 web 写法都支持，但是 weex 里实现的是一个 CSS 的子集，**只能支持 class，并且不支持后代选择器和继承**。还好 weex 中建议使用 flex 布局，更灵活一些，不需要写死了宽度，否则万一一行的图标，由一排4变成了1排5，又要重新改代码算一次了

**Comment by Mr-xue** [comment]
现在的问题不是导航，导航已经ok了。而是其他元素的尺寸问题，按照750的尺寸来写，在web模式下尺寸都没进行缩放适配，元素很大，比如说示例中的字体，而在native下是正常的。

**Comment by icepy** [comment]
@Mr-xue 你的web是否是在钉钉客户端里运行的？

**Comment by Mr-xue** [comment]
我刚试了，在钉钉客户端里运行跟在chrome的手机调试模式下运行都有这个问题，H5下都是按照750的尺寸显示的，没有进行缩放。

**Comment by icepy** [comment]
你的例子里还有id，另外你用了我们那个脚手架吗？刚已经测试过，字体大小是适配的，你可以写一个干净的页面试一试。

**Comment by Mr-xue** [comment]
用的是开始你们文档里开始提供的那个weex-generator-package 链接里面的脚手架，不过前几天，你们又换成dingtalk了。就这个我问题，我还问过你需不需要升级，还给你看过package.json里面的依赖版本，你说没问题。
例子中的id都去掉了，只是dotwe上面没去。

**Comment by icepy** [comment]
我用的是dingtalk init 的，但这两个工程是一样的。

**Comment by Mr-xue** [comment]
![image](https://user-images.githubusercontent.com/11676811/27374075-1b4827d4-569d-11e7-9ed2-29841a95d829.png)
我用dingtalk重建了一份测试项目，也是这个问题，H5模式下会出现尺寸没有进行缩放。
有哪些因素可能会导致这种情况的发生？
