### ISSUE TITLE
仿照钉钉开发文档-如何开启debug功能，没能实现在PC端Chrome中调试钉钉中的weex程序

### ISSUE THREAD

**Issue by nfcookie** [open-dingtalk/weex-dingtalk-issues#6]
浏览器停在这一步
![image](https://user-images.githubusercontent.com/29538201/27278546-485dda00-5514-11e7-96c7-6127ef83359b.png)
钉钉中IM消息打开
![image](https://user-images.githubusercontent.com/29538201/27278615-6ebb09e8-5514-11e7-9c45-5be37a846c5f.png)
浏览器没有进入监听页面

**Comment by icepy** [comment]
![image](https://user-images.githubusercontent.com/3321837/27279358-f8d527a6-5516-11e7-864e-d3b757b03530.png)

需要安装我给你的那个模拟器，最后在模拟器中打开这个页面，前面几个步骤都是对的。

**Comment by nfcookie** [comment]
![image](https://user-images.githubusercontent.com/29538201/27279661-e81170a4-5517-11e7-9107-9e03232d845f.png)
IOS模拟器在哪个文件夹里

**Comment by icepy** [comment]
我发给你的那个.zip包就是，你必须在Mac系统上使用。
