### ISSUE TITLE
debug模式下，控制台报错：CreateListFromArrayLike called on non-object

### ISSUE THREAD

**Issue by Mr-xue** [open-dingtalk/weex-dingtalk-issues#7]
![image](https://user-images.githubusercontent.com/11676811/27313696-d5fada92-55a1-11e7-8c57-69a85fff983b.png)
开始好好的，突然报这个错误，而且有些数据没读过来。问一下是什么原因？

**Comment by icepy** [comment]
定义你错误的代码，给一个复现的demo

**Comment by Mr-xue** [comment]
http://dotwe.org/vue/0f4ab0d4533d45ef653a638ae2d28ec0
记得开跨域插件，要不数据显示不出来。
同样的代码，H5下数据都读出来了。在Native下控制台报错，而且打卡学习跟学分排名模块的数据没读出来

**Comment by icepy** [comment]
我的意思是，你先自己用排除法，删减一些，定位到具体的区域，这样一坨业务代码，我要看很久，效率很低。

**Comment by icepy** [comment]
sortList 初始化声明的时候得是一个数组，我看你的业务上，有根据这个做判断。
